/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DhtRead */

#ifndef _Included_DhtRead
#define _Included_DhtRead
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DhtRead
 * Method:    getTemperature
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DhtRead_getTemperature
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
