/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample_DhtRead */

#ifndef _Included_sample_DhtRead
#define _Included_sample_DhtRead
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample_DhtRead
 * Method:    getTemperature
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sample_DhtRead_getTemperature
  (JNIEnv *, jclass);

/*
 * Class:     sample_DhtRead
 * Method:    getReading
 * Signature: ()Lsample/Reading;
 */
JNIEXPORT jobject JNICALL Java_sample_DhtRead_getReading
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
